scalar Float
### Helper ###

type Global {
  # Always 0
  id: ID!
  activePropertiesCount: Int!
  activePropertiesTotalValuation: BigInt!
  activePropertiesCountryCount: Int!
}

enum PropertyStakingPoolType {
    COMMUNITY
    ISSUER
    RWA
    LANDHIVE
}

enum LimitOrderProtocol {
    ZeroEx
    OneInch
}

### Price Tracking ###

type AssetPairPrice @entity {
  id: ID!
  assetPair: AssetPair!
  timestamp: Int!
  "Timestamp of the hour start (mightnight UTC) in seconds"
  hourStartTimestamp: Int! @index
  "Timestamp of the date start (mightnight UTC) in seconds"
  dayStartTimestamp: Int! @index
  blockNumber: Int!
  priceBI: BigInt!
  price: Float!
}

type AssetPair @entity {
  # ID is the pair of the two assets. Example: ETH/USD or BST/USD
  id: ID!
  latestPrice: Float!
  latestPriceBI: BigInt!
  updatedAt: Int!
  latestAggregatorAddress: Bytes! @index
  prices: [AssetPairPrice!]! @derivedFrom(field: "assetPair")
}

### Marketplace ###

# This is usually a marketplace operator
type CertifiedPartner {
  id: ID!
  chainId: Int!
  name: String! @index
  wallets: [Wallet!]! @derivedFrom(field: "certifiedPartner")
  whitelisted: [UserCertifiedPartner!]! @derivedFrom(field: "certifiedPartner")
  properties: [PropertyToken!]! @derivedFrom(field: "certifiedPartner")
}

type PropertyToken {
  id: ID!
  chainId: Int!
  contractAddress: Bytes! @index
  name: String!
  symbol: String!
  totalSupply: BigInt!
  totalBurnt: BigInt!
  totalTransfers: Int!
  totalHolders: Int!
  tokenValuation: BigInt!
  propertyValuation: BigInt! @index
  propertyValuationUpdateTimestamp: Int!
  propertyValuationCurrency: String!
  # The wallet of the certified partner that the property belongs too
  certifiedPartnerWallet: Wallet!
  streetLocation: String!
  geoLocation: String!
  lat: Float!
  lng: Float!
  countryCode: String!
  parcelNumber: String!
  kadastralMunicipality: String!
  buildingPart: Int!
  propertyType: String!
  ipfs: String!
  createdAt: Int!
  createdAtBlock: Int!
  creationTransaction: String!
  holders: [PropertyTokenHolder!]! @derivedFrom(field: "token")
  capitalStacks: [PropertyTokenCapitalStack!]! @derivedFrom(field: "property")
  oceanpointInformations: [OceanpointTokenInformation!]!
    @derivedFrom(field: "propertyToken")
  investments: [PropertyTokenInvestment!]! @derivedFrom(field: "propertyToken")
  trades: [PropertyTokenTrade!]! @derivedFrom(field: "propertyToken")
  totalPropertyTokenTraded: BigInt!
  totalValueTraded: BigInt!
  transfers: [PropertyTokenTransfer!]! @derivedFrom(field: "propertyToken")
  pendingRevenues: [PropertyTokenRevenue!]! @derivedFrom(field: "propertyToken")
  revenueClaims: [PropertyTokenRevenueClaim!]! @derivedFrom(field: "propertyToken")
  revenueDistributions: [PropertyTokenRevenueDistribution!]!
    @derivedFrom(field: "propertyToken")
  records: [PropertyTokenRecord!]! @derivedFrom(field: "propertyToken")
  certifiedPartner: CertifiedPartner!
  latestOffering: PropertyTokenOffering!
  offerings: [PropertyTokenOffering!]! @derivedFrom(field: "property")
  apy: Float!
  currentYearApy: Float!
  weightedNAVDeviation: Float!
}

# PropertyTokenId + WalletId
type PropertyTokenHolder {
  id: ID!
  chainId: Int!
  amount: BigInt!
  token: PropertyToken!
  wallet: Wallet!
}

# add capital stack on CapitalStackChange event. Don't remove them for history data.
# cap (hardcap) is maximum amount of mintable tokens
type PropertyTokenCapitalStack {
  id: ID! # based on property id + log index
  chainId: Int!
  property: PropertyToken!
  timestamp: Int!
  tokenizationAmount: BigInt!
  commonEquity: BigInt!
  preferredEquity: BigInt!
  mezzanine: BigInt!
  juniorDebt: BigInt!
  seniorDebt: BigInt!
}

type PropertyTokenInvestment {
  id: ID!
  chainId: Int!
  transactionHash: Bytes!
  propertyToken: PropertyToken!
  wallet: Wallet!
  investmentToken: String!
  amountInvested: BigInt!
  amountReceived: BigInt!
  blockTimestamp: Int!
}

type PropertyTokenOffering {
  id: ID!
  chainId: Int!
  property: PropertyToken!
  price: Int!
  softCap: BigInt!
  presaleMaxInvestment: BigInt!
  presaleMinInvestment: BigInt!
  maxInvestment: BigInt!
  minInvestment: BigInt!
  presaleStartTimestamp: Int!
  presaleEndTimestamp: Int!
  saleStartTimestamp: Int!
  saleEndTimestamp: Int!
  investmentToken: String!
  collector: String!
  feeCollector: String!
  fee: BigInt!
  status: String!
}

type PropertyTokenRevenueDistribution {
  id: ID!
  blockTimestamp: Int!
  chainId: Int!
  propertyToken: PropertyToken!
  amounts: [BigInt!]!
  totalAmount: BigInt!
  totalSupply: BigInt!
  propertyValuation: BigInt!
  users: [String!]!
  fromTime: BigInt!
  toTime: BigInt!
}

type PropertyTokenRevenue {
  id: ID!
  chainId: Int!
  propertyToken: PropertyToken!
  wallet: Wallet!
  pendingRevenue: BigInt!
  claimedRevenue: BigInt!
}

type PropertyTokenRevenueClaim {
  id: ID!
  chainId: Int!
  transactionHash: Bytes!
  blockNumber: Int!
  blockTimestamp: Int!
  propertyToken: PropertyToken!
  wallet: Wallet!
  amount: BigInt!
}

type PropertyTokenTrade {
  id: ID!
  chainID: Int!
  transactionHash: Bytes!
  blockNumber: Int!
  blockTimestamp: Int!
  propertyToken: PropertyToken!
  maker: Wallet!
  taker: Wallet!
  orderHash: String!
  makerToken: Bytes!
  takerToken: Bytes!
  takerTokenFilledAmount: BigInt!
  makerTokenFilledAmount: BigInt!
  propertyValuation: BigInt!
  protocol: LimitOrderProtocol!
}

type PropertyTokenTradeCounts {
  id: ID!
  chainId: Int!
  takerCount: Int!
  makerCount: Int!
}

type PropertyTokenTransfer {
  id: ID!
  chainId: Int!
  amount: BigInt!
  blockHash: Bytes!
  blockNumber: Int!
  blockTimestamp: Int!
  from: Wallet!
  logIndex: Int!
  propertyToken: PropertyToken!
  to: Wallet!
  transactionHash: Bytes!
  transactionIndex: Int!
}

type Token {
  id: ID!
  chainId: Int!
  contractAddress: Bytes! @index
  name: String!
  symbol: String!
  totalSupply: BigInt!
  totalBurnt: BigInt!
  totalTransfers: Int!
  totalHolders: Int!
  marketcap: Float!
  marketcapBI: BigInt!
  holders: [TokenHolder!]! @derivedFrom(field: "token")
  historyRecords: [TokenRecord!]! @derivedFrom(field: "token")
}

# TokenId + WalletId
type TokenHolder {
  id: ID!
  chainId: Int!
  amount: BigInt!
  token: Token!
}

type User {
  id: ID!
  chainId: Int!
  wallets: [Wallet!]! @derivedFrom(field: "user")
  certifiedPartners: [UserCertifiedPartner!]! @derivedFrom(field: "user")
}

type UserCertifiedPartner {
  id: ID! # Set to `${user.id}-${certifiedPartner.id}`
  chainId: Int!
  user: User!
  certifiedPartner: CertifiedPartner!
}

type Wallet {
  id: ID!
  address: Bytes! @index
  chainId: Int!
  user: User
  certifiedPartner: CertifiedPartner
  properties: [PropertyTokenHolder!]! @derivedFrom(field: "wallet")
  stakingPositions: [StakingPoolPosition!]! @derivedFrom(field: "wallet")
  stakingV4Positions: [StakingPoolV4Position!]! @derivedFrom(field: "wallet")
  uniswapV4Tokens: [UniswapV4PositionToken!]! @derivedFrom(field: "wallet")
  cumulativeRewards: [UserCumulativeReward!]! @derivedFrom(field: "wallet")
  propertyStakingPositions: [PropertyStakingPoolPosition!]!
    @derivedFrom(field: "wallet")
  takerTrades: [PropertyTokenTrade!]! @derivedFrom(field: "taker")
  makerTrades: [PropertyTokenTrade!]! @derivedFrom(field: "maker")
  senderPropertyTokenTransfers: [PropertyTokenTransfer!]!
    @derivedFrom(field: "from")
  receveiverPropertyTokenTransfers: [PropertyTokenTransfer!]!
    @derivedFrom(field: "to")
  propertyInvestments: [PropertyTokenInvestment!]! @derivedFrom(field: "wallet")
  pendingRevenues: [PropertyTokenRevenue!]! @derivedFrom(field: "wallet")
  revenueClaims: [PropertyTokenRevenueClaim!]! @derivedFrom(field: "wallet")
}

### Oceanpoint ###

type StakingPool {
  id: ID!
  chainId: Int!
  issuedAmount: BigInt!
  stakedAmount: BigInt!
  ratio: BigDecimal!
  currentAmount: BigInt!
  totalDepositAmount: BigInt!
  totalRewards: BigInt!
  totalWithdrawAmount: BigInt!
  positions: [StakingPoolPosition!]! @derivedFrom(field: "pool")
  historyRecords: [StakingPoolRecord!]! @derivedFrom(field: "pool")
}

type StakingPoolPosition {
  id: ID!
  chainId: Int!
  pool: StakingPool!
  wallet: Wallet!
  stakedAmount: BigInt!
  issuedAmount: BigInt! # Multiply this with the current ratio in the pool to get the actual amount
  lockedUntil: Int!
}

type OceanpointTokenInformation {
  id: ID!
  chainId: Int!
  propertyToken: PropertyToken!
  propertyStakingPool: PropertyStakingPool!
  propertyStakingPoolType: PropertyStakingPoolType!
  propertyStakingPoolPositions: [PropertyStakingPoolPosition!]!
    @derivedFrom(field: "tokenInformation")
  valuation: BigInt!
  valuationFrom: Bytes!
  valuePerBSPT: BigInt!
  apy: BigInt!
}

type PropertyStakingPool {
  id: ID!
  chainId: Int!
  issuedAmount: BigInt!
  currentAmount: BigInt!
  totalRewards: BigInt!
  totalRewardsPaid: BigInt!
  currentRewards: BigInt!
  tvl: BigInt!
  tokenInformations: [OceanpointTokenInformation!]!
    @derivedFrom(field: "propertyStakingPool")
  positions: [PropertyStakingPoolPosition!]! @derivedFrom(field: "pool")
  historyRecords: [PropertyStakingPoolRecord!]! @derivedFrom(field: "pool")
}

type TokenDeposit {
  id: ID!
  stakingPoolPosition: PropertyStakingPoolPosition!
  tokenInformation: OceanpointTokenInformation!
  issuedAmount: BigInt!
  stakedAmount: BigInt!
  valuePerBSPT: BigInt!
  lockedUntil: Int!
  stakedValue: BigInt!
}

type PropertyStakingPoolPosition {
  id: ID!
  chainId: Int!
  pool: PropertyStakingPool!
  tokenInformation: OceanpointTokenInformation!
  deposits: [TokenDeposit!]! @derivedFrom(field: "stakingPoolPosition")
  wallet: Wallet!
  totalIssuedAmount: BigInt!
  totalStakedAmount: BigInt!
  totalStakedValue: BigInt!
}

type Reward {
  id: ID!
  chainId: Int!
}

type MarketplacePool {
  id: ID!
  chainId: Int!
  contractAddress: Bytes! @index
  # If the pool reached the full amount of sBST
  capped: Boolean!
  # Initial amount of sBST that the CP add to the pool
  certifiedPartnerCollateralAmount: BigInt!
  # Triggered by owner to allow CP to collect his collateral
  certifiedPartnerCanWithdraw: Boolean!
  certifiedPartnerIdentifier: String!
  certifiedPartnerUrl: String!
  certifiedPartnerWallet: String!
  certifiedPartnerPoolPosition: MarketplacePoolPosition!
  bsWallet: String!
  # Duration in seconds of how long is the investment period
  duration: Int!
  # Duration in seconds of how long users are locked
  lockPeriod: Int!
  # Users can't withdraw before timestamp x
  lockedUntil: Int!
  # sBST staked in the pool
  stakedAmount: BigInt!
  totalDepositAmount: BigInt!
  totalWithdrawAmount: BigInt!
  # Starting max amount of sBST that users can invest (increase over time)
  startMaxPledge: BigInt!
  # Start timestamp when users are allowed to invest
  startTime: Int!
  tokenName: String!
  tokenSymbol: String!
  totalRewardsAdded: BigInt!
  totalRewardsClaimed: BigInt!
  # Internal token amount to track positons.
  vAmount: BigInt!
  positions: [MarketplacePoolPosition!]! @derivedFrom(field: "pool")
  stats: [MarketplacePoolRecord!]! @derivedFrom(field: "pool")
  isCpCollateralLiquidated: Boolean!
  cpCollateralLiquidatedAt: Int!
}

type MarketplacePoolPosition {
  id: ID!
  chainId: Int!
  pool: MarketplacePool!
  wallet: Wallet!
  # sBST stake in the pool
  stakedAmount: BigInt!
  # Internal token amount to track positons.
  vAmount: BigInt!
  rewards: BigInt!
}

### Daily Records ###

type GlobalRecord {
  # Always 0
  id: ID!
  "Timestamp of the hour start (mightnight UTC) in seconds"
  hourStartTimestamp: Int! @index
  "Timestamp of the date start (mightnight UTC) in seconds"
  dayStartTimestamp: Int! @index
  activePropertiesCount: Int!
  activePropertiesTotalValuation: BigInt!
  activePropertiesCountryCount: Int!
}

type MarketplacePoolRecord {
  id: ID!
  chainId: Int!
  "Timestamp of the hour start (mightnight UTC) in seconds"
  hourStartTimestamp: Int! @index
  "Timestamp of the date start (mightnight UTC) in seconds"
  dayStartTimestamp: Int! @index
  pool: MarketplacePool!
  stakedAmount: BigInt!
  totalDepositAmount: BigInt!
  totalWithdrawAmount: BigInt!
  totalRewardsAdded: BigInt!
  totalRewardsClaimed: BigInt!
  vAmount: BigInt!
}

type PropertyStakingPoolRecord {
  id: ID!
  chainId: Int!
  "Timestamp of the hour start (mightnight UTC) in seconds"
  hourStartTimestamp: Int! @index
  "Timestamp of the date start (mightnight UTC) in seconds"
  dayStartTimestamp: Int! @index
  issuedAmount: BigInt!
  currentAmount: BigInt!
  totalRewards: BigInt!
  totalRewardsPaid: BigInt!
  currentRewards: BigInt!
  pool: PropertyStakingPool!
  tvl: BigInt!
}

type PropertyTokenRecord {
  id: ID!
  chainId: Int!
  "Timestamp of the hour start (mightnight UTC) in seconds"
  hourStartTimestamp: Int! @index
  "Timestamp of the date start (mightnight UTC) in seconds"
  dayStartTimestamp: Int! @index
  totalSupply: BigInt!
  totalBurnt: BigInt!
  totalTransfers: Int!
  totalHolders: Int!
  tokenValuation: BigInt!
  propertyValuation: BigInt! @index
  propertyToken: PropertyToken!
  countryCode: String!
}

type StakingPoolRecord {
  id: ID!
  chainId: Int!
  "Timestamp of the hour start (mightnight UTC) in seconds"
  hourStartTimestamp: Int! @index
  "Timestamp of the date start (mightnight UTC) in seconds"
  dayStartTimestamp: Int! @index
  issuedAmount: BigInt!
  stakedAmount: BigInt!
  ratio: BigDecimal!
  currentAmount: BigInt!
  totalDepositAmount: BigInt!
  totalRewards: BigInt!
  totalWithdrawAmount: BigInt!
  pool: StakingPool!
}

type TokenRecord {
  id: ID!
  chainId: Int!
  "Timestamp of the hour start (mightnight UTC) in seconds"
  hourStartTimestamp: Int! @index
  "Timestamp of the date start (mightnight UTC) in seconds"
  dayStartTimestamp: Int! @index
  totalSupply: BigInt!
  totalBurnt: BigInt!
  totalTransfers: Int!
  totalHolders: Int!
  marketcap: Float!
  marketcapBI: BigInt!
  token: Token!
}

type UniswapV4Pool {
  id: ID! # ${chainId}-${poolId}
  chainId: Int!
  poolId: String! @index
  currency0: String!
  currency1: String!
  fee: BigInt!
  tickSpacing: BigInt!
  hooks: String!
  sqrtPriceX96: BigInt!
  tick: BigInt!
  createdAtTimestamp: Int!
  creationTransaction: String!
}

type UniswapV4PoolPosition {
  id: ID! # ${chainId}-${poolId}-${tickLower}-${tickUpper}-${salt}
  uniqueKey: String! @index
  chainId: Int!
  tickLower: BigInt!
  tickUpper: BigInt!
  liquidityDelta: BigInt!
  salt: String!
  amount0: BigInt!
  amount1: BigInt!
  transactionHash: String!
  pool: UniswapV4Pool! @index
  token: [UniswapV4PositionToken!]! @derivedFrom(field: "position")
}

type UniswapV4PoolPositionRecord {
  id: ID! # ${chainId}-${poolId}-${tickLower}-${tickUpper}-${salt}
  blockNumber: Int!
  uniqueKey: String! @index
  chainId: Int!
  tickLower: BigInt!
  tickUpper: BigInt!
  liquidityDelta: BigInt!
  amount0: BigInt!
  amount1: BigInt!
  salt: String!
  transactionHash: String!
  pool: UniswapV4Pool! @index
}

type UniswapV4PositionToken {
  id: ID! # ${chainId}-${tokenId}
  tokenId: BigInt!
  owner: String!
  isBurned: Boolean!
  mintedTransactionHash: String!
  wallet: Wallet!
  position: UniswapV4PoolPosition!
  stakingPosition: [StakingPoolV4Position!]! @derivedFrom(field: "positionToken")
}

type StakingPoolV4 {
  id: ID!
  chainId: Int!
  contractAddress: String!
  positionManager: String!
  targetPoolKey: String!
  minDays: BigInt!
  maxDays: BigInt!
  minBoost: BigInt!
  maxBoost: BigInt!
  earlyPositionSlash: BigInt!
  earlyRewardSlash: BigInt!
  createdAtTimestamp: Int!
  creationTransaction: String!
  totalRewardsAdded: BigInt!
  totalRewardsClaimed: BigInt!
  totalRewardsBurned: BigInt!
  uniswapV4Pool: UniswapV4Pool!
  positions: [StakingPoolV4Position!]! @derivedFrom(field: "pool")
  positionRecords: [StakingPoolV4PositionRecord!]! @derivedFrom(field: "pool")
  historyRecords: [StakingPoolV4Record!]! @derivedFrom(field: "pool")
}

type StakingPoolV4Position {
  id: ID!
  chainId: Int!
  lockedUntil: BigInt!
  timeBoost: BigInt!
  tokenId: BigInt! @index
  liquidity: BigInt!
  isPositionClosed: Boolean!
  updatedAtTimestamp: Int!
  wallet: Wallet!
  pool: StakingPoolV4!
  positionToken: UniswapV4PositionToken
  uniPosition: UniswapV4PoolPosition
}

type StakingPoolV4Record {
  id: ID!
  chainId: Int!
  transactionHash: String!
  totalRewards: BigInt!
  merkleRoot: String!
  pool: StakingPoolV4!
  "Timestamp of the hour start (mightnight UTC) in seconds"
  hourStartTimestamp: Int! @index
  "Timestamp of the date start (mightnight UTC) in seconds"
  dayStartTimestamp: Int! @index
}

enum StakingPoolV4PositionRecordType {
  DEPOSIT
  WITHDRAW
  EARLY_WITHDRAW
  REWARDS_CLAIMED
  REWARDS_BURNED
}

type StakingPoolV4PositionRecord {
  id: ID!
  chainId: Int!
  tokenId: BigInt! @index
  transactionType: StakingPoolV4PositionRecordType!
  transactionHash: String!
  rewardsClaimed: BigInt!
  rewardsBurned: BigInt!
  pool: StakingPoolV4!
  "Timestamp of the hour start (midnight UTC) in seconds"
  hourStartTimestamp: Int! @index
  "Timestamp of the date start (midnight UTC) in seconds"
  dayStartTimestamp: Int! @index
}

type UserCumulativeReward {
  id: ID! # ${stakingPoolId}-${walletAddress}
  cumulativeReward: BigInt!
  claimed: BigInt!
  burned: BigInt!
  lastDistributedCumulativeReward: BigInt!
  updatedAtTimestamp: Int! @index
  blockNumber: Int!
  merkleRoot: String! @index
  proof: [String!]!
  lastDistributedProof: [String!]!
  lastDistributedMerkleRoot: String! @index
  isRewardsDistributed: Boolean!
  distributionSkipped: Boolean!
  wallet: Wallet!
  stakingPool: StakingPoolV4!
  uniPosition: UniswapV4PoolPosition!
}