import fs from 'fs';
import ejs from 'ejs';
import { Config } from '../src/types/config';
import { getLoadedConfig } from '../src/config';

type ConfigOverride = Config & {
  jointValuationContracts: string;
  jointStakingPoolContracts: string;
  jointLiquidityStakingPoolContracts: string;
  jointUniswapPoolContracts: string;
};

if (!process.env.ENVIO_NETWORK) {
  console.error('No ENVIO_NETWORK environment variable set');
  process.exit(1);
}

if (process.env.ENVIO_NETWORK !== 'mainnet' && process.env.ENVIO_NETWORK !== 'testnet') {
  console.error('Invalid ENVIO_NETWORK environment variable set');
  process.exit(1);
}

const loadedConfig = getLoadedConfig();

const configValues: ConfigOverride = {
  ...loadedConfig,
  jointValuationContracts: loadedConfig.propertyStakingContracts
    .map((contract) => contract.valuationAddress)
    .join(','),
  jointStakingPoolContracts: loadedConfig.propertyStakingContracts
    .map((contract) => contract.address)
    .join(','),
  jointUniswapPoolContracts: Object.values(loadedConfig.uniswapPoolContracts)
    .map((contract) => contract.address)
    .join(','),
  jointLiquidityStakingPoolContracts: loadedConfig.liquidityStakingContracts
    .map((contract) => contract.address)
    .join(','),
};

const configTemplate = fs.readFileSync(
  `./templates/template.${process.env.ENVIO_NETWORK}.config.yaml`,
  'utf8',
);

const configString = ejs.render(configTemplate, { config: configValues });

const generationWarning = `### This file is autogenerated from the template.config.yaml file in the root of the project ###
### Edit the template.config.yaml file in the root of the project and run \`npm run codegen\` to update this file ###
`;

try {
  // Write the envio config file only
  fs.writeFileSync('./config.yaml', generationWarning + configString);
  console.log(`✅ Generated config.yaml for ${process.env.ENVIO_NETWORK}`);
} catch (e) {
  console.log(e);
}
